version: '3'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - mern-app
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db

  node:
    restart: always
    # build: .
    build:
      context: ./server
      # dockerfile: ./server/Dockerfile
    ports:
      - 5000:5000
    networks:
      - mern-app
    depends_on:
      - mongo
    volumes:
      - ./:/code

  mern-todolist:
    container_name: mern-todolist
    build:
      context: ./client
      # dockerfile: ./client/Dockerfile
    # volumes:
    #   - '.:/client'
    #   - './client/node_modules'
    ports:
      - '8080:80'
    networks:
      - mern-app
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development

networks:
  mern-app:
    driver: bridge
volumes:
  mongodb_data_container:
# version: '3.7'
# services:
#   mongodb_container:
#     image: mongo:latest
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: rootpassword
#     ports:
#       - 27017:27017
#     volumes:
#       - mongodb_data_container:/data/db

# volumes:
#   mongodb_data_container:

# version: '3'
# services:
#   react-app:
#     image: react-app
#     stdin_open: true
#     ports:
#       - '3000:3000'
#     networks:
#       - mern-app
#   api-server:
#     image: api-server
#     ports:
#       - '5000:5000'
#     networks:
#       - mern-app
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo:3.6.19-xenial
#     ports:
#       - '27017:27017'
#     networks:
#       - mern-app
#     volumes:
#       - mongo-data:/data/db
# networks:
#   mern-app:
#     driver: bridge
# volumes:
#   mongo-data:
#     driver: local
