version: '3'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - mern-app
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db

  node:
    restart: always
    build:
      context: ./server
    ports:
      - 5000:5000
    networks:
      - mern-app
    depends_on:
      - mongo
    volumes:
      - ./:/code

  mern-todolist:
    container_name: mern-todolist
    build:
      context: ./client
    ports:
      - '8080:80'
    networks:
      - mern-app
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development

networks:
  mern-app:
    driver: bridge
volumes:
  mongodb_data_container:
